sudo: true
language: haskell

git:
  depth: 5

cabal: "2.2"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.4.4

install:
  - ghc --version
  - cabal --version
  - cabal new-update

script:
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint src/

notifications:
  email: false
